name: "mqtt-io"
description: >-
  "HA plug-in for the popular flyte/mqtt-io service"
version: "1.0.0"
slug: "mqtt-io"
init: false
url: "https://github.com/pmgledhill102/addon-mqtt-io"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl
services:
  - mqtt:need
startup: application
gpio: true
privileged: SYS_RAWIO
